<?php 

function expert_form_alter(&$form,&$form_state,$form_id) {
  //print_r($form_id);
  if($form_id == 'best_answer_node_form' && arg(3) == 'expert' && arg(2) == 'best-answer' ){
    //pay attention to this term 39 it's only work on ask for expert
    //术语ID为39,表示专家类型的提问,添加CSS去处"在光标处截断摘要"
		drupal_add_css(drupal_get_path('module','expert').'/expert.css');
    $form['taxonomy']['8']['#default_value'] =  39; 
    $form['taxonomy']['8']['#attributes'] = array('disabled'=>TRUE,); 
  }
}
