<?php
 // $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $
 
  // Plugin definition
  $plugin = array(
           'title' => t('inner'),
           //'icon' => 'test.png',
           'theme' => 'inner',
           'css' => 'inner.css',
           //'admin css' => 'quiz_admin.css',
           'panels' => array(
                      'dy4' => t('dy4'),
                      'dy6' => t('dy6'),
                      'zy4' => t('zy4'),
                      'zy8' => t('zy8'),
                      'gyyy' => t('gyyy'),
                      'pets' => t('pets'),
                      ),
);