<?php                                                                                                                                                        
 // $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $                                                                                        
                                                                                                                                                             
 // Plugin definition                                                                                                                                        
 $plugin = array(                                                                                                                                            
          'title' => t('ztfenlei'),                                                                                                                             
          //'icon' => 'test.png',                                                                                                                            
          'theme' => 'ztfenlei',                                                                                                                                
          'css' => 'ztfenlei.css',                                                                                                                              
          //'admin css' => 'quiz_admin.css',                                                                                                                 
          'panels' => array(                                                                                                                                 
                     'swyy_fenlei' => t('swyy_fenlei'),                                                                                                                  
                     'kjyy_fenlei' => t('kjyy_fenlei'),                                                                                                                    
                     'gqwh_fenlei' => t('gqwh_fenlei'),                                                                                                                    
                     'tyyy_fenlei' => t('tyyy_fenlei'),                                                                                                                                                                                                                                       
                     ),                                                                                                                                      
); 
