<?php

$plugin = array(
          'title' => t('21st'),
          'theme' => '21st',
          'css' => '21st.css',
          'admin css' => '21st_admin.css',
          'panels' => array(
                     'zq_title_21st' => t('zq_title-21st'),
                     'zq_content_21st' => t('zq_content_21st'),
		     'box_21st' => t('box_21st'),
		     'column_21st_l1' => t('column_21st_l1'),
		     'column_21st_l2' => t('column_21st_l2'),
		     'column_21st_r1' => t('column_21st_r1'),
		     'column_21st_r2' => t('column_21st_r2'),
		     'dl_21st' => t('dl_21st'),
                     ),
);

