<?php
// $Id: comment_closer.install,v 1.1.2.3 2009/01/10 19:07:05 rmiddle Exp $
/**
 * @file
 */

/**
 * Implementation of hook_uninstall().
 */
function comment_closer_uninstall() {
  variable_del('comment_closer_age');
  variable_del('comment_closer_cycle_period');
  variable_del('comment_closer_next_date');
  variable_del('comment_closer_types');

  drupal_set_message(t('Comment Closer module uninstalled.'));
}
