<?php                                                                                                                                                        
 // $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $                                                                                        
                                                                                                                                                             
  // Plugin definition                                                                                                                                       
  $plugin = array(                                                                                                                                           
           'title' => t('zhuanjia'),                                                                                                                            
           'theme' => 'zhuanjia',                                                                                                                               
           'css' => 'zhuanjia.css',                                                                                                                             
           'panels' => array(                                                                                                                                
                      'left' => t('content_left'),                                                                                                                     
                      'right' => t('content_right'),                                                                                                                                                                                                                                                            
                      ),                                                                                                                                     
); 
