<?php
function drupal_discuz_block($op = 'list', $delta = 0, $edit = array()){
  if ($op == 'list') {
    $blocks[0]['info'] = t('DISCUZ 各版块最新的帖子');
    $blocks[0]['cache'] = BLOCK_CACHE_GLOBAL;
    
    $blocks[1]['info'] = t('DISCUZ 最新资源');
    $blocks[1]['cache'] = BLOCK_CACHE_GLOBAL;
    
    $blocks[2]['info'] = t('UHOME 博客精华');
    $blocks[2]['cache'] = BLOCK_CACHE_GLOBAL; 
    return $blocks;
  }
	
  if($op == 'view'){
  	$block = array();
    switch ($delta) {
      case 0:
	      	$block['subject'] = t('社区');
		  	$block['content'] = get_discuz_newpost(5);
		  	return $block;
      case 1:
	      	$block['subject'] = t('热门资源');
		  	$block['content'] = discuz_source(7);
		  	return $block;
      case 2:
	      	$block['subject'] = t('博客精华');
		  	$block['content'] = uhome_hotblog(7,4);
		  	return $block; 	 
    }
  }   
}


/*
 *   获取论坛各版块 中最新的一篇帖子
 *   @wzs 20100518
 * 
 */

function get_discuz_newpost($num=10){
	global $discuz_url ;
	$discuz_url = "http://u.2u4u.com.cn/";
	db_set_active('discuz');	
	$sql = "SELECT uf.name, uf.lastpost, ut.fid, ut.tid
			FROM `uu_forums` uf
			LEFT JOIN `uu_threads` ut ON ut.fid = uf.fid
			GROUP BY ut.fid
			ORDER BY ut.dateline DESC LIMIT %d";
	
	$rs = db_query($sql,$num);
	while($row = db_fetch_object($rs)){
		  if(strpos($row->lastpost,"	"))
	           $array = explode("	",$row->lastpost);
		   $content .= "<ul><li>[<a href='".$discuz_url."bbs/forumdisplay.php?fid=".$row->fid."'  target='_blank'>".$row->name."</a>]
		   <a href='".$discuz_url."bbs/viewthread.php?tid=".$array[0]."'  target='_blank'>".$array[1]."</a></li><ul>";
		
	}
	db_set_active('default');
	return $content;
}

/*
 *   论坛的最新资源
 */

function discuz_source($num =10){
        $discuz_url = "http://u.2u4u.com.cn/";
        db_set_active('discuz');
	$sql = "SELECT ut.subject, ua.filetype,ut.tid
			FROM `uu_attachments` ua
			LEFT JOIN `uu_threads` ut ON ua.tid = ut.tid
			WHERE ut.fid >0
			AND ut.fid
			IN ( 23, 28, 35, 39, 43 ) 
			GROUP BY ua.tid
			ORDER BY ua.dateline DESC LIMIT %d";
	
	$rs = db_query($sql,$num);
	while($row = db_fetch_object($rs)){
		
          switch($row->filetype){
		    case "application/msword":
                    case "application/octet-stream":
		         $img = "doc.gif";
		         break;
		    case "application/x-zip-compressed":
		    	 $img = "rar.gif";
		         break;
		    case "application/vnd.ms-powerpoint":
		    	 $img = "ppt.gif";
		         break;
		    case "application/pdf":
		    	 $img = "pdf.gif";
		         break;
		    
        }
        
        $img = !empty($img)?$img:'notsure.gif'; 
         $img_url = "http://cdn1.2u4u.com.cn/2u4u.banners/";       
		$content .= "<ul><li><span><img src='".$img_url.$img."'></span><a href='".$discuz_url."bbs/viewthread.php?tid=".$row->tid."'  target='_blank'>".$row->subject."</a></li>";
		
		
	}
	
	db_set_active('default');
	return $content;
}

/*
 *   首页热门博客
 *   默认取一周中四篇博客，按热门排行
 *   
 */
function uhome_hotblog($day=7,$num=4){		
     $discuz_url = "http://u.2u4u.com.cn/";
     db_set_active('uchome');
     $time = strtotime("today");
    $sql = "SELECT blogid,uid,username,subject 
		    FROM `uchome_blog` 
		     GROUP BY uid ORDER BY hot DESC,viewnum DESC 
		     LIMIT $num";		    
    $rs = db_query($sql);
//var_dump($rs);
    DEFINE('UC_API',"http://u.2u4u.com.cn/ucenter"); 
    while($row = db_fetch_object($rs)){
    	$photo = '';
    	$photo = ckavatar($row->uid) ? avatar($row->uid, 'small',true) : UC_API.'/images/noavatar_small.gif';
    	$content .=  "<div class='qz-blog-row'><div class='qz-bk-pic'><a href='".$discuz_url."home/space.php?uid=".$row->uid."'  target='_blank'><img src ='".$photo."'></a></div>";
    	$content .= "<div class='qz-bk-title'><a href='".$discuz_url."home/space.php?uid=".$row->uid."'  target='_blank'>".$row->username."</a></div>";
        $content .= "<div class='qz-bk-text'><a href='".$discuz_url."home/space.php?uid=".$row->uid."&do=blog&id=".$row->blogid."'  target='_blank'>".$row->subject."</a></div></div>";
    	
    }
    
	db_set_active('default');
	return $content;	    
		    
}
function avatar($uid, $size='small', $returnsrc = FALSE) {
	
	$size = in_array($size, array('big', 'middle', 'small')) ? $size : 'small';
	$avatarfile = avatar_file($uid, $size);
	return $returnsrc ? UC_API.'/data/avatar/'.$avatarfile : '<img src="'.UC_API.'/data/avatar/'.$avatarfile.'" onerror="this.onerror=null;this.src=\''.UC_API.'/images/noavatar_'.$size.'.gif\'">';
}

function avatar_file($uid, $size) {
	global $_SGLOBAL, $_SCONFIG;

	$type = empty($_SCONFIG['avatarreal'])?'virtual':'real';
	$var = "avatarfile_{$uid}_{$size}_{$type}";
	if(empty($_SGLOBAL[$var])) {
		$uid = abs(intval($uid));
		$uid = sprintf("%09d", $uid);
		$dir1 = substr($uid, 0, 3);
		$dir2 = substr($uid, 3, 2);
		$dir3 = substr($uid, 5, 2);
		$typeadd = $type == 'real' ? '_real' : '';
		$_SGLOBAL[$var] = $dir1.'/'.$dir2.'/'.$dir3.'/'.substr($uid, -2).$typeadd."_avatar_$size.jpg";
	}
	return $_SGLOBAL[$var];
}

function ckavatar($uid) {
	    $_SCONFIG['uc_dir'] = '/home/apache/data/html/ucenter/ucenter';
		$file = $_SCONFIG['uc_dir'].'/data/avatar/'.avatar_file($uid, 'middle');
		return file_exists($file)?1:0;
	
}
?>
