<?php 

/*检查核心profile完整性
 * 
 */

   function  checkCoreProfile_user($op, &$edit, &$account, $category = NULL)
   {
       if ($op == 'update') {
           drupal_set_message("请开始测试");
	   drupal_goto("award");
       }
   }

   function checkCoreProfile_form_alter(&$form, &$form_state, $form_id){
        $check_form_id = 'quiz_question_answering_form';
   	if($form_id == $check_form_id ){
  	     global $user;
	     $sql="select * from  profile_values  where fid=6 and uid=%d";
             $result =  db_query($sql,$user->uid);
             while ($data = db_fetch_object($result))
             {
                   $id= $data->value;
              }
	      if(empty($id)){
		  drupal_set_message("请补充完整用户信息后再参加测试");
		  drupal_goto("user/$user->uid/edit/个人信息");
	      }
 	   }   
	 

   } 


