<?php
 // $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $
 
 // Plugin definition
 $plugin = array(
          'title' => t('frame'),
          //'icon' => 'test.png',
          'theme' => 'frame',
          'css' => 'frame.css',
          //'admin css' => 'quiz_admin.css',
          'panels' => array(
                     'lunbo' => t('lunbo'),
                     'zdtj' => t('zdtj'),
                     'csfl' => t('csfl'),
                     'ad_1' => t('ad_1'),
		     'zxtk' => t('zxtk'),
		     'ksrl' => t('ksrl'),
                     'ad_2' => t('ad_2'),
                     'ad_3' => t('ad_3'),
                     'dfphb' => t('dfphb'),
	             'zxlx' => t('zxlx'),
                     'ztcs' => t('ztcs'),
                     'ztcsphb' => t('ztcsphb'),
                     'qwcs' => t('qwcs'),
                     'qwcsphb' => t('qwcsphb'),
                     ),      
);
