<?php 

$plugin = array(                                                                                                                 
          'title' => t('fenlei'),                                                                                           
          //'icon' => 'frame.png',                                                                                                
          'theme' => 'fenlei',                                                                                               
          'css' => 'fenlei.css',                                                                                            
          'admin css' => 'fenlei_admin.css',                                                         
          'panels' => array(                                                                                             
                     'fenlei1' => t('fenlei1'),
                     'fenlei2' => t('fenlei2'),
                     'fenlei3' => t('fenlei3'),                                                                     
                     'fenlei4' => t('fenlei4'),  
                     'fenlei5' => t('fenlei5'),
		     'fenlei6' => t('fenlei6'),
		     'fenlei7' => t('fenlei7'),
                     ),
);
