<?php 

$plugin = array(                                                                                                                 
          'title' => t('smlx'),                                                                                           
          //'icon' => 'test.png',                                                                                                
          'theme' => 'smlx',                                                                                               
          'css' => 'smlx.css',                                                                                            
          'admin css' => 'smlx_admin.css',                                                         
          'panels' => array(                                                                                             
                     'smart_pic' => t('smart_pic'),
                     'smart_everyday' => t('smart_everyday'),
                     'smart_category' => t('smart_category'),                                                                     
                     'smart_qa' => t('smart_qa'),  
                     ),
);
