<?php
// $Id$

function orderdelete_menu() {
  $items['admin/settings/orderdelete'] = array(
    'title'            => 'Batch delete order',
    'page callback'    => 'drupal_get_form',
	  'page arguments'    =>  array('orderdelete_form'),
    'access arguments' => array('administer site configuration'),
    'weight'           => 1,
    'type'             => MENU_NORMAL_ITEM,
   
  );

  return $items;
}

function orderdelete_form(){

	$form['submit'] = array(
		'#type' =>'submit',
		'#value' => t('Delete'),
	);
	return $form;
}
function orderdelete_form_submit($form,&$form_state){
	$types = array_filter($form_state['values']['types']);
	$batch =array(
		'operations' => array(
		  array('orderdelete_process', array($types)),
		  ),
		'finished' => 'orderdelete_finished',
		'title' => t('删除订单'),
		'init_message' => t('开始批量删除.'),
		//'progress_message' => t('Reindexed @current out of @total.'),
		'error_message' => t('批量删除遇到错误.'),
	);
	batch_set($batch);
}
function orderdelete_process(&$context){
	$size =100;
	//$types_str ='story,page';
	//$types_str = "'".implode("','", $types)."'";
	if(!isset($context['sandbox']['progress'])){
		$context['sandbox']['progress'] = 0;
		$context['sandbox']['last_order_id'] = 0;
		$context['sandbox']['max'] =db_result(db_query("SELECT count(order_id) FROM uc_orders "));
	}
	$sql = "SELECT order_id  FROM {uc_orders} WHERE order_id > %d ORDER BY order_id ASC";
	$result = db_query_range($sql, $context['sandbox']['last_order_id'], 0, $size);
	while($item = db_fetch_object($result)){
		//node_delete($node['nid']);
		$delete = FALSE;
		$order = uc_order_load($item->order_id);
		//当订单总额大于0,并且订单不是积分商品时,删除订单
		if($order->order_total > 0.01 && !($order->moneyable) ){
		  	//	$delete =  TRUE;
				//$context['message'] = t('删除节点 %order_id',array('%order_id' => $item->order_id));
				drupal_set_message(t('删除节点 %order_id',array('%order_id' => $item->order_id)));
		}
		
		if($delete){
		  uc_order_delete($item->order_id);
		}
		
		$context['sandbox']['progress']++;
		$context['sandbox']['last_order_id'] =$item->order_id;
		//$context['message'] = t('删除节点 %nid',array('%nid' => $node['nid']));
	}
	if($context['sandbox']['progress'] ==$context['sandbox']['max']){
		$context['finished'] = 1;
	}else{
		$context['finished'] = $context['sandbox']['progress']/$context['sandbox']['max'];
	}

}

function orderdelete_finished($success, $results, $operations){
	if ($success) {
		// Here we do something meaningful with the results.
		$message = t('订单删除完成');
		
	}
	else {
		// An error occurred.
		// $operations contains the operations that remained unprocessed.
		$error_operation = reset($operations);
		$message = '在删除订单时出现一个错误'. $error_operation[0] .' 其参数为 :'. print_r($error_operation[0], TRUE);
	}
	drupal_set_message($message);
}
