<?php
 // $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $
 
  // Plugin definition
  $plugin = array(
           'title' => t('zhuticeshi'),
           //'icon' => 'test.png',
           'theme' => 'zhuticeshi',
           'css' => 'zhuticeshi.css',
           //'admin css' => 'quiz_admin.css',
           'panels' => array(
                      'swyy' => t('swyy'),
                      'kjyy' => t('kjyy'),
                      'gqwh' => t('gqwh'),
                      'tyyy' => t('tyyy'),
                      'yyxzs' => t('yyxzs'),
                      'kongde' => t('kongde'),
                      ),
);
