<?php                                                                                                                                                        
// $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $                                                
                                                                                                             
// Plugin definition                                                                                                                                       
$plugin = array(                                                                                                        
	   'title' => t('zxlx'),                                                                                        
	   'theme' => 'zxlx', 	   
	   'css' => 'zxlx.css',                                                                                   
	   //'admin css' => 'zxlx_admin.css',	   
           'panels' => array(                                                
	              'zuo' => t('zuo'),  
                      'zhong' => t('zhong'),                                                       
                      'you' => t('you'),                                                
	   ),                                                                                                                           
); 
