<?php 

$plugin = array(                                                                                                                 
          'title' => t('frame'),                                                                                           
          //'icon' => 'frame.png',                                                                                                
          'theme' => 'frame',                                                                                               
          'css' => 'frame.css',                                                                                            
          'admin css' => 'frame_admin.css',                                                         
          'panels' => array(                                                                                             
                     'classic_left' => t('classic_left'),
                     'classic_flash' => t('classic_flash'),
                     'classic_show_list' => t('classic_show_list'),                                                                     
                     'classic_right' => t('classic_right'),  
                     'classic_note' => t('classic_note'),
                     'classic_elearning' => t('classic_elearning'),
                     'classic_ad' => t('calssic_ad'),
                     ),
);
