<?php
// $Id: sina_open.module,v 1.5 2011/02/11 03:52:44 eastcn Exp $

/**
 * @file
 * 实现新浪微博开放平台部分功能
 */

/**
 * Implementation of hook_menu.
 */
function sina_open_menu() {
  
  $items['sina_open/t_login'] = array(
    'description' => '新浪微博登录或绑定',
    'page callback' => 'sina_open_page_t_login',
    'access callback' => 'sina_open_is_access',
    'type' => MENU_CALLBACK,
    'file' => 'sina_open.pages.inc',
  );
  
  $items['user/%user/sina_open/config'] = array(
    'title' => '新浪微博设置',
    'page callback' => 'sina_open_page_config',
    'page arguments' => array(1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'sina_open.pages.inc',
  );
  $items['user/%user/sina_open/remove'] = array(
    'title' => '新浪微博解除绑定',
    'page callback' => 'sina_open_page_config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sina_open_remove_confirm', 1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => 'sina_open.pages.inc',
  );
  $items['admin/settings/sina_open'] = array(
    'title' => '新浪微博',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sina_open_admin_settings'),
    'access arguments' => array('administer sina open'),
    'file' => 'sina_open.admin.inc',
  );
  $items['admin/settings/sina_open/users'] = array(
    'title' => '微博用户',
    'page callback' => 'sina_open_admin_users',
    'access arguments' => array('administer sina open'),
    'file' => 'sina_open.admin.inc',
  );
  return $items;
}

/**
 * @Implement of hook_perm()
 */
function sina_open_perm() {
  return array('administer sina open');
}

/**
 * 使用新浪微博登录或绑定帐号的权限
 */
function sina_open_is_access() {
  global $user;
  return $user->uid > 0 || variable_get('sina_open_is_login', 1);
}

/**
 * Implementation of hook_form_alter
 */
function sina_open_form_alter(&$form, $form_state, $form_id) {
  if (variable_get('sina_open_is_login', 1) && ($form_id == 'user_login_block' || $form_id == 'user_login')) {
    
    $form['sina_open_links'] = array(
      '#value' => theme('item_list', array(array(
        'data' => l('使用新浪微博登录', 'sina_open/t_login'),
        'class' => 'sina_open_login_links'
      ))),
      '#weight' => 1,
    );
    
  }
  
  global $user;
  $sina_open = false;
  
  if ('comment_form' == $form_id) {
    if (variable_get('sina_open_comment', 1)) {
      if ($user->uid > 0) { 
        $sina_open = true;
      } else {
        
        if (variable_get('comment_form_location_'. $node->type, COMMENT_FORM_SEPARATE_PAGE) == COMMENT_FORM_SEPARATE_PAGE) {
          $destination = 'redirect='. rawurlencode('comment/reply/'.$form['nid']['#value']);
        } else {
          $destination = 'redirect='. rawurlencode('node/'.$form['nid']['#value']);
        }
        
        $form['sina_open_links'] = array(
          '#value' => theme('item_list', array(array(
            'data' => l('使用新浪微博登录', 'sina_open/t_login', array('query' => $destination)),
            'class' => 'sina_open_login_links'
          ))),
          '#weight' => -2,
        );
      }
    }
  }else if (isset($form['#node']) && $form['#node']->type .'_node_form' == $form_id
  && variable_get('sina_open_node_'.$form['#node']->type, 1) && !$form['#node']->nid) {
    $sina_open = true;
  }
  
  if ($sina_open) {
    $form['sina_open'] = array(
      '#type' => 'fieldset',
      '#title' => '发送到新浪微博',
      '#collapsible' => true,
      '#collapsed' => true,
      '#tree' => true
    );
    $form['sina_open']['check'] = array(
      '#type' => 'radios',
      '#title' => '发送',
      '#required' => true,
      '#default_value' => 0,
      '#options' => array('否', '是'),
    );
    $form['sina_open']['title'] = array(
      '#type' => 'textfield',
      '#title' => '内容',
      '#description' => '访问 url 将附加在内容后面，总字数不大于 140，留空将使用标题。需要先绑定微博帐号才能使用此功能。',
    );
  }
  return $form;
}

/**
 * @Implement of hook_nodeapi()
 */
function sina_open_nodeapi(&$node, $op) {
  if ($op == 'insert' && variable_get('sina_open_node_'.$node->type, 1) && $node->sina_open) {
    global $user;
    
    if($node->sina_open['check']) {
      if (db_result(db_query('SELECT uid FROM {sina_open_user} WHERE uid = %d', $user->uid))) {
        $url = url('node/'.$node->nid, array('absolute' => true));
        
        sina_open_t_set_tweet(
          $node->sina_open['title'] ? $node->sina_open['title'] : $node->title,
          url('node/'.$node->nid, array('absolute' => true))
        );
      } else {
        drupal_set_message('您需要先绑定新浪微博帐号，才能够推送信息。', 'error');
      }
    }

  }
}

/**
 * @Implement of hook_comment()
 */
function sina_open_comment(&$comment, $op) {
  if ($op == 'insert' && isset($comment['sina_open']) && variable_get('sina_open_comment', 1)) {
    if($comment['sina_open']['check']) {
      sina_open_t_set_tweet(
        $comment['sina_open']['title'] ? $comment['sina_open']['title'] : $comment['subject'],
        url('node/'.$comment['nid'], array('absolute' => true, 'fragment' => 'comment-'. $comment['cid']))
      );
    }
  }
}

/**
 * @Implement of hook_user()
 */
function sina_open_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load': // case 'login':
      $result = db_query('SELECT * FROM {sina_open_user} WHERE uid = %d', $account->uid);
      if ($o = db_fetch_object($result)) {
        if ($o->token) {
          $o->token = unserialize($o->token);
        }
        
        if (empty($o->sina_uid)) {
          sina_open_is_token(true);
        }
        
        $account->sina_open_t = $o;
      }
    break;
    case 'delete':
      db_query('DELETE FROM {sina_open_user} WHERE uid = %d', $account->uid);
    
  }
}

/**
 * 编码数据
 * @param (string or array) $input
 */
function sina_open_urlencode_rfc3986($input) { 
  if (is_array($input)) { 
      return array_map('sina_open_urlencode_rfc3986', $input); 
  } else if (is_scalar($input)) { 
    return str_replace( '+', ' ',  str_replace('%7E', '~', rawurlencode($input))); 
  } else { 
    return ''; 
  } 
}

/**
 * GET query 字符串解析为数组
 * @param (string) $string
 */
function sina_open_parse_parameters($string) { 
  if (!isset($string) || !$string) return array(); 

  $pairs = explode('&', $string); 

  $param = array(); 
  foreach ($pairs as $pair) { 
    $split = explode('=', $pair, 2); 
    $parameter = urldecode($split[0]); 
    $value = isset($split[1]) ? urldecode($split[1]) : ''; 

    if (isset($param[$parameter])) { 
      if (is_scalar($param[$parameter])) { 
        $param[$parameter] = array($param[$parameter]); 
      } 
      $param[$parameter][] = $value; 
    } else { 
      $param[$parameter] = $value; 
    } 
  } 
  return $param; 
}

/**
 * 获取用户访问令牌
 * @param (int) $uid
 */
function sina_open_get_access_token($uid = 0) {
  static $datas;
  
  if (!isset($datas) || !isset($datas[$uid])) {
    if ($uid > 0) {
      if ($o = db_fetch_object(db_query('SELECT uid, token FROM {sina_open_user} WHERE uid = %d', $uid))) {
        if ($o->token) {
          $datas[$uid] = unserialize($o->token);
        } else {
          drupal_set_message('您的新浪微博授权已经过期，请'.l('点击这儿', 'sina_open/t_login').'重新授权');
        }
      }
    } else {
      $datas[$uid] = false;
    }
  }
  
  return $datas[$uid];
}

/**
 * 创建 http 请求
 * @param (array) $params
 */
function sina_open_t_get_request(array $params) {
  $request = new stdClass;
  if (!$consumer_key = variable_get('sina_open_oauth_consumer_key', false)) {
    $consumer_key = 401055340;
  } else {
    $consumer_secret = variable_get('sina_open_oauth_consumer_secret', false);
  }
  
  // 默认参数
  $defaults = array( 
    'oauth_version' => '1.0a', // 版本
    'oauth_nonce' => md5(mt_rand(). $_SERVER['REQUEST_TIME']), // 随机数
    'oauth_timestamp' => time(), // 发起请求的时间戳
    'oauth_consumer_key' => $consumer_key, // app key
    'oauth_consumer_secret' => $consumer_secret, // app 密钥
    'oauth_signature_method' => 'HMAC-SHA1', // 签名方式
  );
  
  // 合并
  $params = array_merge($defaults, $params);
  
  if (isset($params['oauth_consumer_key'])) {
    $request->consumer->key = $params['oauth_consumer_key'];
  } else {
    //$params['oauth_consumer_key'] = $request->consumer->key = 401055340;
    drupal_set_message('必须提供 sina app key', 'error');
    return false;
  }
  
  if (isset($params['oauth_consumer_secret']) && $params['oauth_consumer_secret']) {
    $request->consumer->secret = $params['oauth_consumer_secret'];
    unset($params['oauth_consumer_secret']);
  } else {
    $request->consumer->secret = NULL;
  }
  
  // 访问令牌
  $request->token = NULL;
  if (isset($params['oauth_access_token_key'])) {
    $request->token->key = $params['oauth_access_token_key'];
    unset($params['oauth_access_token_key']);
  }
  
  if (isset($params['oauth_access_token_secret'])) {
    $request->token->secret = $params['oauth_access_token_secret'];
    unset($params['oauth_access_token_secret']);
  }
  
  if (!$request->token && $GLOBALS['user']->uid > 0) {
    $request->token = sina_open_get_access_token($GLOBALS['user']->uid);
  }
  
  if ($request->token->key && !isset($params['oauth_token'])) {
    $params['oauth_token'] = $request->token->key;
  }
  
  if (isset($params['http_method'])) {
    $request->http_method = $params['http_method'];
    unset($params['http_method']);
  } else {
    $request->http_method = 'POST';
  }
  
  if (isset($params['http_url'])) {
    $request->http_url = $params['http_url'];
    unset($params['http_url']);
  } else {
    return false;
  }
  
  // 参数中不允许包含签名
  if (isset($params['oauth_signature'])) {
    unset($params['oauth_signature']);
  }
  
  $keys = sina_open_urlencode_rfc3986(array_keys($params));
  $values = sina_open_urlencode_rfc3986(array_values($params));
  $params = array_combine($keys, $values);
  
  uksort($params, 'strcmp');

  $pairs = $urls = array();
  
  foreach ($params as $key => $value ) {
    if (is_array($value)) {
      natsort($value);
      
      foreach ($value as $v2) {
        $pairs[] = $key . '=' . $v2;
        $urls[] = $key . '[]=' . $v2;
      }
    } else {
      $pairs[] = $key . '=' . $value;
      $urls[] = $key . '=' . $value;
    }
  }
  
  $parts = array($request->http_method, $request->http_url, implode('&', $pairs));
  
  // 待签名基本字符串
  $request->base_string = implode('&', sina_open_urlencode_rfc3986($parts));
  
  if ($request->consumer->secret) {
  
    $key_parts = array(
      $request->consumer->secret,
      $request->token ? $request->token->secret : ""
    );
    
    $key_parts = sina_open_urlencode_rfc3986($key_parts);
    $key = implode('&', $key_parts);
    
    $request->sign = base64_encode(hash_hmac('sha1', $request->base_string, $key, true));
    
  } else {
    $request->sign = sina_open_http_get_sign(
      $request->consumer->key,
      $request->base_string,
      ($request->token ? $request->token->secret : "")
    );
  }
  
  
  if (!$request->sign) {
    drupal_set_message('无法取得签名', 'error');
    return false;
  }
  
  $urls[] = 'oauth_signature='.sina_open_urlencode_rfc3986($request->sign);
  
  $request->to_data = implode('&', $urls);
  
  return $request;
}

/**
 * 远程获取签名，若自行申请 sina app key，不需要远程获取
 * @param (int) $consumer_key
 * @param (string) $base_string
 * @param (string) $token_secret
 */
function sina_open_http_get_sign($consumer_key, $base_string, $token_secret = NULL) {
  $headers = array(
    'User-Agent' => 'Sae T OAuth v0.2.0-beta2',
    'Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8'
  );
  
  $data = 'consumer_key='.sina_open_urlencode_rfc3986($consumer_key). '&';
  $data .= 'base_string='.sina_open_urlencode_rfc3986($base_string);
  
  if ($token_secret) {
    $data .= '&token_secret='.sina_open_urlencode_rfc3986($token_secret);
  }
  
  $data .= '&base_url='.sina_open_urlencode_rfc3986($GLOBALS['base_url']);
  
  $result = drupal_http_request('http://www.didaah.org/sot?op=get_sign', $headers, 'POST', $data);
  
  if ($result->code == 200 && $result->data && substr($result->data, 0, 2) == 'ok') {
    return substr($result->data, 2);
  }
}

/**
 * 将 destination 参数注销，防止使用 drupal_goto 时，跳转到该地址
 */
function sina_open_get_redirect() {
  if (isset($_REQUEST['destination'])) {
    if (!isset($_REQUEST['redirect'])) {
      $_REQUEST['redirect'] = $_REQUEST['destination'];
    }
    unset($_REQUEST['destination']);
  }
  
  if (isset($_REQUEST['redirect'])) {
    return 'redirect='.$_REQUEST['redirect'];
  }
}

/**
 * 获取授权令牌，让用户使用此链接跳转到新浪进行授权
 * @param (array) $values
 */
function sina_open_t_login_url(array $values = array()) {
  if (!isset($values['http_url'])) {
    // 请求未授权令牌 url
    $values['http_url'] = 'http://api.t.sina.com.cn/oauth/request_token';
  }
  
  if (isset($_GET['oauth_callback'])) {
    $oauth_callback = $_GET['oauth_callback'];
  } else if (isset($values['oauth_callback'])) {
    $oauth_callback = $values['oauth_callback'];
    unset($values['oauth_callback']);
  } else {
    if ($redirect = sina_open_get_redirect()) {
      $redirect = '&' . $redirect;
    } else {
      $redirect = '';
    }
    $oauth_callback = url('sina_open/t_login', array('query' => 'op=validate'.$redirect, 'absolute' => true));
  }
  
  if (!$request = sina_open_t_get_request($values)) {
    return false;
  }
  
  $headers = array(
    'User-Agent' => 'Sae T OAuth v0.2.0-beta2',
    'Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8'
  );
  
  $result = drupal_http_request($request->http_url, $headers, 'POST', $request->to_data);
  if ($result->data && strpos($result->data, 'oauth_token_secret') !== false) {
    $token = sina_open_parse_parameters($result->data);
    if ($token['oauth_token_secret']) {
      $tok = new stdClass;
      $tok->key = $token['oauth_token'];
      $tok->secret = $token['oauth_token_secret'];
      
      $_SESSION['sina_t_oauth_token'] = $tok;
      
      $url = 'http://api.t.sina.com.cn/oauth/authenticate';
      $url .= '?oauth_token='.$token['oauth_token'];
      $url .= '&oauth_callback='.urlencode($oauth_callback);
      return $url;
    }
  }
  
  // 未能成功获取授权令牌
  
  return false;
}

/**
 * 获取访问令牌，用户已授权，根据授权令牌获得访问令牌
 * @param (array) $values
 */
function sina_open_t_access_token(array $values = array()) {
  if (!isset($values['http_url'])) {
    $values['http_url'] = 'http://api.t.sina.com.cn/oauth/access_token';
  }
  
  if (!isset($values['oauth_verifier']) && isset($_GET['oauth_verifier'])) {
    $values['oauth_verifier'] = $_GET['oauth_verifier'];
  }
  
  if (!isset($values['oauth_token']) && isset($_GET['oauth_token'])) {
    $values['oauth_token'] = $_GET['oauth_token'];
  }
  
  if (!isset($values['oauth_access_token_key']) && isset($_SESSION['sina_t_oauth_token'])) {
    $values['oauth_access_token_key'] = $_SESSION['sina_t_oauth_token']->key;
    $values['oauth_access_token_secret'] = $_SESSION['sina_t_oauth_token']->secret;
  }
  
  $result = sina_open_t_set_request($values['http_url'], $values);
  
  if ($result->data) {
    $token = sina_open_parse_parameters($result->data);
    if ($token['oauth_token_secret']) {
      unset($_SESSION['sina_t_oauth_token']);
      $tok = new stdClass;
      
      // 访问令牌
      $tok->key = $token['oauth_token'];
      $tok->secret = $token['oauth_token_secret'];
      $tok->verifier = $values['oauth_verifier'];
      
      return $tok;
    }
  }
}

/**
 * 执行一个 http 请求
 */
function sina_open_t_set_request($http_url, array $values = array(), array $headers = array(), $method = 'POST') {
  if (!isset($headers['User-Agent'])) {
    $headers['User-Agent'] = 'Sae T OAuth v0.2.0-beta2';
  }
  
  if (!isset($headers['Content-Type'])) {
    $headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=utf-8';
  }
  
  $values['http_url'] = $http_url;
  $values['http_method'] = $method;
  
  if (!$request = sina_open_t_get_request($values)) {
    return false;
  }
  
  return drupal_http_request($request->http_url, $headers, $method, $request->to_data);
}

/**
 * 获取用户绑定的微博基本信息
 */
function sina_open_t_get_info($ac) {
  $data = db_fetch_object(db_query('SELECT uid, token FROM {sina_open_user} WHERE uid = %d', $ac->uid));
  
  if (isset($data->uid)) { 
    if ($result = sina_open_t_set_request('http://api.t.sina.com.cn/account/verify_credentials.json')) {
      if ($result->code == 200) {
        
        $data = json_decode($result->data);
        
      } else {
        drupal_set_message('授权已过期，请重新获取授权', 'error');
      }
      
    }
  } else {
    drupal_set_message('还没有绑定微博', 'error');
  }
  
  return $data;
}

/**
 * 发布微博表单
 * @param (array) &$form_state
 * @param (int) $uid
 */
function sina_open_set_tweet_form(&$form_state, $uid) {
  $form['sina_open_tweet_text'] = array(
    '#type' => 'textarea',
    '#title' => '发布到新浪微博',
    '#description' => '最多140个字符，中英文均算一个字符。还可以输入<strong id="sina_open_tweet_text_count"></strong>个字符。',
    '#required' => 1
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '确认发布'
  );
  drupal_add_js(drupal_get_path('module', 'sina_open') .'/sina_open.js');
  return $form;
}

function sina_open_set_tweet_form_validate($form, &$form_state) {
  $form_state['values']['sina_open_tweet_text'] = trim($form_state['values']['sina_open_tweet_text']);
  if (drupal_strlen($form_state['values']['text']) > 140) {
    form_set_error('sina_open_tweet_text', '不大于 140 个字符');
  } else if (!sina_open_t_set_tweet($form_state['values']['sina_open_tweet_text'])) {
    form_set_error('sina_open_tweet_text', '请重试');
  }
}

/**
 * 发送一条微博
 * @param (string) $text
 *  文字内容
 * @param (string) $url
 *  访问地址
 */
function sina_open_t_set_tweet($text, $url = NULL) {
  if (isset($url)) {
    $len = drupal_strlen($url);
  } else {
    $len = 0;
  }
  
  $len = 140 - drupal_strlen($text) + $len;
  
  if ($len < 0) {
    $text = drupal_substr($text, 0, $len);
  }
  
  $result = sina_open_t_set_request(
    'http://api.t.sina.com.cn/statuses/update.json',
    array('status' => urlencode($text. $url))
  );
  
  if ($result->code == 200) {
    drupal_set_message('已成功发送到新浪微博');
  } else {
    drupal_set_message('发送到新浪微博失败', 'error');
    return false;
  }
  
  return $result;
}

/**
 * 验证当前用户新浪微博访问令牌是否过期，若过期则尝试使用旧的验证码再次获取，不成功则提示
 * @param (bool) $clear
 *  立即验证
 */
function sina_open_is_token($clear = NULL) {
  global $user;
  
  if ($user->uid > 0) {
    
    if (!isset($clear)) {
      
      if (isset($_SESSION['sina_open_is_validate_timestamp'])) {
        if ($_SESSION['sina_open_is_validate_timestamp'] === true) {
          // 用户没有绑定新浪微博
          return true;
        } else if (($_SERVER['REQUEST_TIME']-300) < $_SESSION['sina_open_is_validate_timestamp']) {
          // 上次验证在五分钟之内
          return true;
        }
      }
    
    }
    if ($o = db_fetch_object(db_query("SELECT sina_uid, uid, token FROM {sina_open_user} WHERE sina_name = '%s'", $user->name))) {
      
      if ($o->token) {
        $_SESSION['sina_t_oauth_access_token'] = unserialize($token);
      }
      
      $_SESSION['sina_open_is_validate_timestamp'] = $_SERVER['REQUEST_TIME'];
      
    } else {
      $_SESSION['sina_open_is_validate_timestamp'] = true;
    }
    
    if (isset($_SESSION['sina_t_oauth_access_token'])) {
      $result = sina_open_t_set_request('http://api.t.sina.com.cn/account/verify_credentials.json');
      if ($result->code == 200) {
        
        if (empty($o->sina_uid)) {
          $json = json_decode($result->data);
          if (!empty($json->id)) {
            db_query("UPDATE {sina_open_user} SET sina_uid = '%s' WHERE uid = %d", $json->uid, $user->uid);
          }
        }
        
        return true;
      } else if ($tok = sina_open_t_access_token()) {
        // 尝试使用旧的 token 和 verify 重新获取访问令牌
        return true;
      } else {
        unset($_SESSION['sina_t_oauth_access_token']);
        drupal_set_message('您的新浪微博授权已经过期，请'.l('点击这儿', 'sina_open/t_login').'重新授权');
      }
    }
    
  }
}