<?php
 // $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $
 
  // Plugin definition
  $plugin = array(
           'title' => t('quweiceshi'),
           //'icon' => 'test.png',
           'theme' => 'quweiceshi',
           'css' => 'quweiceshi.css',
           //'admin css' => 'quiz_admin.css',
           'panels' => array(
                      'yscb' => t('yscb'),
                      'xgzb' => t('xgzb'),
                      'xlzd' => t('xlzd'),
                      'lazn' => t('lazn'),
                      'zcpc' => t('zcpc'),
                      'shcf' => t('shcf'),
                      'jktj' => t('jktj'),
                      'xzys' => t('xzys'),
                      'sspw' => t('sspw'), 
                      ),
);
