<?php                                                                                                                                                        
 // $Id: twocol.inc,v 1.1.2.2 2010/01/13 06:25:15 merlinofchaos Exp $                                                                                        
                                                                                                                                                             
 // Plugin definition                                                                                                                                        
 $plugin = array(                                                                                                                                            
          'title' => t('qwfenlei'),                                                                                                                             
          //'icon' => 'test.png',                                                                                                                            
          'theme' => 'qwfenlei',                                                                                                                                
          'css' => 'qwfenlei.css',                                                                                                                              
          //'admin css' => 'quiz_admin.css',                                                                                                                 
          'panels' => array(                                                                                                                                 
                     'yscb_fenlei' => t('yscb_fenlei'),                                                                              
                     'xlzd_fenlei' => t('xlzd_fenlei'),                                                                          
                     'xgzb_fenlei' => t('xgzb_fenlei'),                                                                                
		     'lazn_fenlei' => t('lazn_fenlei'),     
                     'shcf_fenlei' => t('shcf_fenlei'),
                     'zccp_fenlei' => t('zccp_fenlei'),
		     'xzys_fenlei' => t('xzys_fenlei'),		     
		     'sspw_fenlei' => t('sspw_fenlei'),
		     'jktj_fenlei' => t('jktj_fenlei'),
                     ),                                                                                                                                      
); 
