<?php 

$plugin = array(                                                                                                                 
          'title' => t('category'),                                                                                           
          //'icon' => 'test.png',                                                                                                
          'theme' => 'category',                                                                                               
          'css' => 'category.css',                                                                                            
          'admin css' => 'category_admin.css',                                                         
          'panels' => array(                                                                                             
                     'category_idioms' => t('category_idioms'),
                     'category_slang' => t('category_slang'),
                     ),
);
